// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiConversation struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	EstimateID pgtype.UUID        `json:"estimate_id"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AiConversationMessage struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Model          pgtype.Text        `json:"model"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AiEstimate struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	ImageKey       pgtype.Text        `json:"image_key"`
	PromptVersion  string             `json:"prompt_version"`
	Provider       string             `json:"provider"`
	Model          string             `json:"model"`
	Status         string             `json:"status"`
	Confidence     pgtype.Numeric     `json:"confidence"`
	MealType       string             `json:"meal_type"`
	LoggedOn       pgtype.Date        `json:"logged_on"`
	Locale         string             `json:"locale"`
	UnitSystem     string             `json:"unit_system"`
	Question       pgtype.Text        `json:"question"`
	Questions      []byte             `json:"questions"`
	Warnings       []byte             `json:"warnings"`
	RawModelJson   []byte             `json:"raw_model_json"`
	NormalizedJson []byte             `json:"normalized_json"`
	AcceptedLogID  pgtype.UUID        `json:"accepted_log_id"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
	ReviewedStatus pgtype.Text        `json:"reviewed_status"`
	ReviewNotes    pgtype.Text        `json:"review_notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AiEstimateItem struct {
	ID            uuid.UUID          `json:"id"`
	EstimateID    uuid.UUID          `json:"estimate_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Name          string             `json:"name"`
	MatchedFoodID pgtype.UUID        `json:"matched_food_id"`
	QuantityG     pgtype.Numeric     `json:"quantity_g"`
	CaloriesKcal  pgtype.Numeric     `json:"calories_kcal"`
	ProteinG      pgtype.Numeric     `json:"protein_g"`
	CarbsG        pgtype.Numeric     `json:"carbs_g"`
	FatG          pgtype.Numeric     `json:"fat_g"`
	Confidence    pgtype.Numeric     `json:"confidence"`
	Source        string             `json:"source"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AiUsageEvent struct {
	ID             uuid.UUID          `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	EstimateID     pgtype.UUID        `json:"estimate_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Provider       string             `json:"provider"`
	Model          string             `json:"model"`
	Operation      string             `json:"operation"`
	Status         string             `json:"status"`
	LatencyMs      int32              `json:"latency_ms"`
	InputTokens    int32              `json:"input_tokens"`
	OutputTokens   int32              `json:"output_tokens"`
	ErrorClass     pgtype.Text        `json:"error_class"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DailyNutrientTotal struct {
	UserID     uuid.UUID          `json:"user_id"`
	LoggedOn   pgtype.Date        `json:"logged_on"`
	NutrientID uuid.UUID          `json:"nutrient_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	Unit       string             `json:"unit"`
	Amount     pgtype.Numeric     `json:"amount"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DriValue struct {
	ID         uuid.UUID          `json:"id"`
	NutrientID uuid.UUID          `json:"nutrient_id"`
	LifeStage  string             `json:"life_stage"`
	Sex        pgtype.Text        `json:"sex"`
	Amount     pgtype.Numeric     `json:"amount"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EmailVerification struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	UserID    uuid.UUID          `json:"user_id"`
	FoodID    uuid.UUID          `json:"food_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Food struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	Name         string             `json:"name"`
	Brand        pgtype.Text        `json:"brand"`
	Category     string             `json:"category"`
	ServingSizeG pgtype.Numeric     `json:"serving_size_g"`
	Source       string             `json:"source"`
	Verified     bool               `json:"verified"`
	Barcode      pgtype.Text        `json:"barcode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ImageUrl     pgtype.Text        `json:"image_url"`
}

type FoodNutrient struct {
	FoodID        uuid.UUID      `json:"food_id"`
	NutrientID    uuid.UUID      `json:"nutrient_id"`
	AmountPer100g pgtype.Numeric `json:"amount_per_100g"`
}

type FoodNutrientDailyValue struct {
	FoodID            uuid.UUID          `json:"food_id"`
	NutrientID        uuid.UUID          `json:"nutrient_id"`
	DailyValuePercent pgtype.Numeric     `json:"daily_value_percent"`
	Source            string             `json:"source"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MealLog struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	LoggedOn  pgtype.Date        `json:"logged_on"`
	MealType  string             `json:"meal_type"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MealLogItem struct {
	ID        uuid.UUID          `json:"id"`
	MealLogID uuid.UUID          `json:"meal_log_id"`
	UserID    uuid.UUID          `json:"user_id"`
	FoodID    uuid.UUID          `json:"food_id"`
	ServingG  pgtype.Numeric     `json:"serving_g"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationEvent struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	NotificationType string             `json:"notification_type"`
	Title            string             `json:"title"`
	Body             string             `json:"body"`
	Data             []byte             `json:"data"`
	Status           string             `json:"status"`
	Error            pgtype.Text        `json:"error"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	UserID                    uuid.UUID          `json:"user_id"`
	RecommendationPushEnabled bool               `json:"recommendation_push_enabled"`
	WeeklySummaryPushEnabled  bool               `json:"weekly_summary_push_enabled"`
	AiInsightsPushEnabled     bool               `json:"ai_insights_push_enabled"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type Nutrient struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Unit          string             `json:"unit"`
	NutrientGroup string             `json:"nutrient_group"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PasswordReset struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PushDevice struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	DeviceID   uuid.UUID          `json:"device_id"`
	FcmToken   string             `json:"fcm_token"`
	Platform   string             `json:"platform"`
	AppVersion string             `json:"app_version"`
	Locale     string             `json:"locale"`
	Timezone   string             `json:"timezone"`
	Enabled    bool               `json:"enabled"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Reminder struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      pgtype.Text        `json:"body"`
	RemindAt  pgtype.Timestamptz `json:"remind_at"`
	Timezone  string             `json:"timezone"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ReminderTemplate struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Trigger   string             `json:"trigger"`
	Audience  string             `json:"audience"`
	Sent7d    int32              `json:"sent_7d"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Ip               *netip.Addr        `json:"ip"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Role            string             `json:"role"`
	SuspendedAt     pgtype.Timestamptz `json:"suspended_at"`
	FirebaseUid     pgtype.Text        `json:"firebase_uid"`
}

type UserProfile struct {
	UserID                uuid.UUID          `json:"user_id"`
	DisplayName           string             `json:"display_name"`
	Sex                   pgtype.Text        `json:"sex"`
	DateOfBirth           pgtype.Date        `json:"date_of_birth"`
	HeightCm              pgtype.Numeric     `json:"height_cm"`
	WeightKg              pgtype.Numeric     `json:"weight_kg"`
	ActivityLevel         pgtype.Text        `json:"activity_level"`
	Units                 string             `json:"units"`
	Locale                string             `json:"locale"`
	Timezone              string             `json:"timezone"`
	Preferences           []byte             `json:"preferences"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PregnancyStatus       pgtype.Text        `json:"pregnancy_status"`
	DietaryPattern        pgtype.Text        `json:"dietary_pattern"`
	Allergens             []string           `json:"allergens"`
	Goals                 []string           `json:"goals"`
	AvatarUrl             pgtype.Text        `json:"avatar_url"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
}
