// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyNutrientTotal struct {
	UserID     uuid.UUID          `json:"user_id"`
	LoggedOn   pgtype.Date        `json:"logged_on"`
	NutrientID uuid.UUID          `json:"nutrient_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	Unit       string             `json:"unit"`
	Amount     pgtype.Numeric     `json:"amount"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DriValue struct {
	ID         uuid.UUID          `json:"id"`
	NutrientID uuid.UUID          `json:"nutrient_id"`
	LifeStage  string             `json:"life_stage"`
	Sex        pgtype.Text        `json:"sex"`
	Amount     pgtype.Numeric     `json:"amount"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EmailVerification struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	UserID    uuid.UUID          `json:"user_id"`
	FoodID    uuid.UUID          `json:"food_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Food struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	Name         string             `json:"name"`
	Brand        pgtype.Text        `json:"brand"`
	Category     string             `json:"category"`
	ServingSizeG pgtype.Numeric     `json:"serving_size_g"`
	Source       string             `json:"source"`
	Verified     bool               `json:"verified"`
	Barcode      pgtype.Text        `json:"barcode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type FoodNutrient struct {
	FoodID        uuid.UUID      `json:"food_id"`
	NutrientID    uuid.UUID      `json:"nutrient_id"`
	AmountPer100g pgtype.Numeric `json:"amount_per_100g"`
}

type MealLog struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	LoggedOn  pgtype.Date        `json:"logged_on"`
	MealType  string             `json:"meal_type"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MealLogItem struct {
	ID        uuid.UUID          `json:"id"`
	MealLogID uuid.UUID          `json:"meal_log_id"`
	UserID    uuid.UUID          `json:"user_id"`
	FoodID    uuid.UUID          `json:"food_id"`
	ServingG  pgtype.Numeric     `json:"serving_g"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Nutrient struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	Unit          string             `json:"unit"`
	NutrientGroup string             `json:"nutrient_group"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PasswordReset struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      pgtype.Text        `json:"body"`
	RemindAt  pgtype.Timestamptz `json:"remind_at"`
	Timezone  string             `json:"timezone"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Ip               *netip.Addr        `json:"ip"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserProfile struct {
	UserID          uuid.UUID          `json:"user_id"`
	DisplayName     string             `json:"display_name"`
	Sex             pgtype.Text        `json:"sex"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	HeightCm        pgtype.Numeric     `json:"height_cm"`
	WeightKg        pgtype.Numeric     `json:"weight_kg"`
	ActivityLevel   pgtype.Text        `json:"activity_level"`
	Units           string             `json:"units"`
	Locale          string             `json:"locale"`
	Timezone        string             `json:"timezone"`
	Preferences     []byte             `json:"preferences"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PregnancyStatus pgtype.Text        `json:"pregnancy_status"`
	DietaryPattern  pgtype.Text        `json:"dietary_pattern"`
	Allergens       []string           `json:"allergens"`
	Goals           []string           `json:"goals"`
}
