// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, refresh_token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, NULLIF($5, '')::inet, $6)
RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Column5          interface{}        `json:"column_5"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CreateSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.Column5,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByID = `-- name: GetActiveSessionByID :one
SELECT id, user_id, expires_at, created_at
FROM sessions
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveSessionByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveSessionByID(ctx context.Context, id uuid.UUID) (GetActiveSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByID, id)
	var i GetActiveSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByRefreshHash = `-- name: GetActiveSessionByRefreshHash :one
SELECT id, user_id, expires_at, created_at
FROM sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveSessionByRefreshHashRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActiveSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (GetActiveSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByRefreshHash, refreshTokenHash)
	var i GetActiveSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET refresh_token_hash = $2,
    expires_at = $3
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, expires_at, created_at
`

type RotateSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type RotateSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (RotateSessionRow, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i RotateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
