// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFirebaseUser = `-- name: CreateFirebaseUser :one
INSERT INTO users (id, email, firebase_uid, email_verified_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, firebase_uid, email_verified_at, created_at, updated_at
`

type CreateFirebaseUserParams struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	FirebaseUid     pgtype.Text        `json:"firebase_uid"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

type CreateFirebaseUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	FirebaseUid     pgtype.Text        `json:"firebase_uid"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateFirebaseUser(ctx context.Context, arg CreateFirebaseUserParams) (CreateFirebaseUserRow, error) {
	row := q.db.QueryRow(ctx, createFirebaseUser,
		arg.ID,
		arg.Email,
		arg.FirebaseUid,
		arg.EmailVerifiedAt,
	)
	var i CreateFirebaseUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirebaseUid,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreateUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING user_id, display_name, units, locale, timezone, preferences, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
}

type CreateUserProfileRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Units       string             `json:"units"`
	Locale      string             `json:"locale"`
	Timezone    string             `json:"timezone"`
	Preferences []byte             `json:"preferences"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (CreateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.UserID, arg.DisplayName)
	var i CreateUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Units,
		&i.Locale,
		&i.Timezone,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMe = `-- name: GetMe :one
SELECT
    u.id,
    u.email,
    u.email_verified_at,
    u.created_at,
    p.display_name,
    p.units,
    p.locale,
    p.timezone,
    p.preferences
FROM users u
JOIN user_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetMeRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DisplayName     string             `json:"display_name"`
	Units           string             `json:"units"`
	Locale          string             `json:"locale"`
	Timezone        string             `json:"timezone"`
	Preferences     []byte             `json:"preferences"`
}

func (q *Queries) GetMe(ctx context.Context, id uuid.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Units,
		&i.Locale,
		&i.Timezone,
		&i.Preferences,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, email_verified_at, created_at, updated_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, email, password_hash, firebase_uid, email_verified_at, created_at, updated_at
FROM users
WHERE firebase_uid = $1 AND deleted_at IS NULL
`

type GetUserByFirebaseUIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	FirebaseUid     pgtype.Text        `json:"firebase_uid"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid pgtype.Text) (GetUserByFirebaseUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i GetUserByFirebaseUIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirebaseUid,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, email_verified_at, created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkFirebaseUser = `-- name: LinkFirebaseUser :one
UPDATE users
SET firebase_uid = $2,
    email_verified_at = COALESCE(users.email_verified_at, $3)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, firebase_uid, email_verified_at, created_at, updated_at
`

type LinkFirebaseUserParams struct {
	ID              uuid.UUID          `json:"id"`
	FirebaseUid     pgtype.Text        `json:"firebase_uid"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

type LinkFirebaseUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	FirebaseUid     pgtype.Text        `json:"firebase_uid"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LinkFirebaseUser(ctx context.Context, arg LinkFirebaseUserParams) (LinkFirebaseUserRow, error) {
	row := q.db.QueryRow(ctx, linkFirebaseUser, arg.ID, arg.FirebaseUid, arg.EmailVerifiedAt)
	var i LinkFirebaseUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirebaseUid,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
